default:
  beschaeftigungsverbot:
    pre: 56
    post: 56
  wochengeld:
    selbststaendig: 57.89
    geringfuegig: 9.78
  tagsatz:
    min: 33.88
    max: 66
  kbgKonto:
    maxDuration: 851
    amount1Parent: 12366
    amount2Parents: 15449
  einkommensabhaengig:
    beschaeftigtDauer: 182

